### ISSUE TITLE
with @loopback/rest doesn't work

### ISSUE THREAD

**Issue by AdamSmid** [arondn2/loopback4-example-websocket#1]
Hello im trying to make this example working with @loopback/rest package and @loopback/rest-explorer
and it not working. 

I have made a fork of this example and implemented basic things of RestApplication

Do you have any idea why i cant connect to the /ws/chats ? 

https://github.com/AdamSmid/loopback4-example-websocket

**Comment by AdamSmid** [comment]
Ok, i made some changes. The problem was:
` RestApplication' defines instance member property 'start', but extended class 'WebsocketSampleApplication' defines it as instance member function.
`
and
` RestApplication' defines instance member property 'stop', but extended class 'WebsocketSampleApplication' defines it as instance member function.
`

I have changed the functions to:
`start = async() => {
     await this.wsServer.start();
   };

   stop = async() => {
    await this.wsServer.stop();
  };
`

And it works now

**Comment by AdamSmid** [comment]
Ok, i made some changes. The problem was:
`RestApplication' defines instance member property 'start', but extended class 'WebsocketSampleApplication' defines it as instance member function.`
and
`RestApplication' defines instance member property 'stop', but extended class 'WebsocketSampleApplication' defines it as instance member function.`

I have changed the functions to:
`
start = async() => {
await this.wsServer.start();
};

stop = async() => {
await this.wsServer.stop();
};
`

And it works now

**Comment by alexkander** [comment]
Hi, I tested your repo and found this solution:
https://gist.github.com/arondn2/61b5bc9bc30bd44e4b298d3c85e9c273.

Also, here is more tips https://github.com/arondn2/loopback4-extension-websocket/. It may have some errors. I am working on it.

Please, close this issue if you think this resolve your problem.

Regards.

**Comment by AdamSmid** [comment]
Ahh, thanks :) it works great.
